config/routes.rb
Rails.application.routes.draw do
  resources :ruby_win_sources

  get 'welcome/index'
  resources :articles

   root 'welcome#index'
  get 'sign-up' => 'home#sign_up'

end

app/models/ruby_win_source.rb
class RubyWinSource < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ruby_win_sources_controller.rb
class RubyWinSourcesController < ApplicationController
  before_action :set_ruby_win_source, only: [:show, :edit, :update, :destroy]

  # GET /ruby_win_sources
  # GET /ruby_win_sources.json
  def index
    @ruby_win_sources = RubyWinSource.all
  end

  # GET /ruby_win_sources/1
  # GET /ruby_win_sources/1.json
  def show
  end

  # GET /ruby_win_sources/new
  def new
    @ruby_win_source = RubyWinSource.new
  end

  # GET /ruby_win_sources/1/edit
  def edit
  end

  # POST /ruby_win_sources
  # POST /ruby_win_sources.json
  def create
    @ruby_win_source = RubyWinSource.new(ruby_win_source_params)

    respond_to do |format|
      if @ruby_win_source.save
        format.html { redirect_to @ruby_win_source, notice: 'Ruby win source was successfully created.' }
        format.json { render :show, status: :created, location: @ruby_win_source }
      else
        format.html { render :new }
        format.json { render json: @ruby_win_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ruby_win_sources/1
  # PATCH/PUT /ruby_win_sources/1.json
  def update
    respond_to do |format|
      if @ruby_win_source.update(ruby_win_source_params)
        format.html { redirect_to @ruby_win_source, notice: 'Ruby win source was successfully updated.' }
        format.json { render :show, status: :ok, location: @ruby_win_source }
      else
        format.html { render :edit }
        format.json { render json: @ruby_win_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ruby_win_sources/1
  # DELETE /ruby_win_sources/1.json
  def destroy
    @ruby_win_source.destroy
    respond_to do |format|
      format.html { redirect_to ruby_win_sources_url, notice: 'Ruby win source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ruby_win_source
      @ruby_win_source = RubyWinSource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ruby_win_source_params
      params.require(:ruby_win_source).permit(:username)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ruby_win_sources_helper.rb
module RubyWinSourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ruby_win_sources/_form.html.erb
<%= form_for(@ruby_win_source) do |f| %>
  <% if @ruby_win_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ruby_win_source.errors.count, "error") %> prohibited this ruby_win_source from being saved:</h2>

      <ul>
      <% @ruby_win_source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ruby_win_sources/edit.html.erb
<h1>Editing ruby_win_source</h1>

<%= render 'form' %>

<%= link_to 'Show', @ruby_win_source %> |
<%= link_to 'Back', ruby_win_sources_path %>

app/views/ruby_win_sources/index.html.erb
<h1>Listing ruby_win_sources</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ruby_win_sources.each do |ruby_win_source| %>
      <tr>
        <td><%= ruby_win_source.username %></td>
        <td><%= link_to 'Show', ruby_win_source %></td>
        <td><%= link_to 'Edit', edit_ruby_win_source_path(ruby_win_source) %></td>
        <td><%= link_to 'Destroy', ruby_win_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ruby win source', new_ruby_win_source_path %>

app/views/ruby_win_sources/new.html.erb
<h1>New ruby_win_source</h1>

<%= render 'form' %>

<%= link_to 'Back', ruby_win_sources_path %>

app/views/ruby_win_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @ruby_win_source.username %>
</p>

<%= link_to 'Edit', edit_ruby_win_source_path(@ruby_win_source) %> |
<%= link_to 'Back', ruby_win_sources_path %>

app/views/welcome/index.html.erb
<h1>USER LOGIN</h1>
<form id="signup" name="signup">
	<label for="email">Email id</label>
	<input class="text" name="email" type="text"/>
	<label for="username">username</label>
	<input class="text username" name="username" type="text"/>
	<input class="btn" type="submit" value="sign-up"/>
         
</form>
<img src="http://2.bp.blogspot.com/-PvTvQXE_EqY/UJUoC0S_glI/AAAAAAAANRU/MejdTCp7j58/s1600/White+Desktop+Wallpapers+and+Backgrounds+3.jpg width="800" height="500"  ">